import type { Metadata } from "next";
import { Inter, Rokkitt } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

Inter({ subsets: ["latin"] });
Rokkitt({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        <Navbar />
        <main>{children}</main>
        {/* <Footer></Footer> */}
      </body>
    </html>
  );
}
